fix error with phpunit10 (undefined method setMethods())
 Was removed in phpunit10

 Error: Call to undefined method PHPUnit\Framework\MockObject\MockBuilder::setMethods()